"""init2

Revision ID: 53d62ad6af26
Revises: c3949d266cfa
Create Date: 2026-07-23 20:15:42.216570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d62ad6af26'
down_revision: Union[str, None] = 'c3949d266cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('invite_token', sa.String(length=8), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True),
    sa.Column('session_key_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organisation_slug'), 'organisation', ['slug'], unique=True)
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piece_name'), 'piece', ['name'], unique=True)
    op.create_table('access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('permission_level', sa.String(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_token_organisation_id'), 'access_token', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_access_token_token_hash'), 'access_token', ['token_hash'], unique=True)
    op.create_table('organisation_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organisation_id', name='uq_organisation_role_name_org')
    )
    op.create_index(op.f('ix_organisation_role_organisation_id'), 'organisation_role', ['organisation_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('permission_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_organisation_id'), 'user', ['organisation_id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_user_id'), 'player', ['user_id'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_token_hash'), 'session', ['token_hash'], unique=True)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('user_organisation_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_role_id'], ['organisation_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organisation_role_id')
    )
    op.create_table('bag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'name', name='uq_bag_player_name')
    )
    op.create_index(op.f('ix_bag_player_id'), 'bag', ['player_id'], unique=False)
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='friendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('requester_player_id', sa.Integer(), nullable=False),
    sa.Column('recipient_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_player_id', 'recipient_player_id', name='uq_friend_requester_recipient')
    )
    op.create_index(op.f('ix_friend_recipient_player_id'), 'friend', ['recipient_player_id'], unique=False)
    op.create_index(op.f('ix_friend_requester_player_id'), 'friend', ['requester_player_id'], unique=False)
    op.create_table('bag_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bag_id', 'piece_id', name='uq_bag_piece_bag_piece')
    )
    op.create_index(op.f('ix_bag_piece_bag_id'), 'bag_piece', ['bag_id'], unique=False)
    op.create_index(op.f('ix_bag_piece_piece_id'), 'bag_piece', ['piece_id'], unique=False)
    op.create_table('game_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'claimed', name='gameinvitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('inviter_player_id', sa.Integer(), nullable=False),
    sa.Column('invitee_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_invite_game_id'), 'game_invite', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_invite_invitee_player_id'), 'game_invite', ['invitee_player_id'], unique=False)
    op.create_index(op.f('ix_game_invite_inviter_player_id'), 'game_invite', ['inviter_player_id'], unique=False)
    op.create_table('game_player_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('game_player_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_player_id'], ['game_player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_player_id', 'piece_id', name='uq_game_player_piece_seat_piece')
    )
    op.create_index(op.f('ix_game_player_piece_game_player_id'), 'game_player_piece', ['game_player_id'], unique=False)
    op.create_index(op.f('ix_game_player_piece_piece_id'), 'game_player_piece', ['piece_id'], unique=False)
    op.add_column('game', sa.Column('is_game_over', sa.Boolean(), nullable=False))
    op.add_column('game', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('game', sa.Column('winner_player_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'player', ['winner_player_id'], ['id'], ondelete='SET NULL')
    op.drop_column('game', 'is_completed')
    op.add_column('game_player', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_game_player_player_id'), 'game_player', ['player_id'], unique=False)
    op.create_foreign_key(None, 'game_player', 'player', ['player_id'], ['id'], ondelete='SET NULL')
    op.drop_column('game_player', 'player_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_player', sa.Column('player_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game_player', type_='foreignkey')
    op.drop_index(op.f('ix_game_player_player_id'), table_name='game_player')
    op.drop_column('game_player', 'player_id')
    op.add_column('game', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'winner_player_id')
    op.drop_column('game', 'created_at')
    op.drop_column('game', 'is_game_over')
    op.drop_index(op.f('ix_game_player_piece_piece_id'), table_name='game_player_piece')
    op.drop_index(op.f('ix_game_player_piece_game_player_id'), table_name='game_player_piece')
    op.drop_table('game_player_piece')
    op.drop_index(op.f('ix_game_invite_inviter_player_id'), table_name='game_invite')
    op.drop_index(op.f('ix_game_invite_invitee_player_id'), table_name='game_invite')
    op.drop_index(op.f('ix_game_invite_game_id'), table_name='game_invite')
    op.drop_table('game_invite')
    op.drop_index(op.f('ix_bag_piece_piece_id'), table_name='bag_piece')
    op.drop_index(op.f('ix_bag_piece_bag_id'), table_name='bag_piece')
    op.drop_table('bag_piece')
    op.drop_index(op.f('ix_friend_requester_player_id'), table_name='friend')
    op.drop_index(op.f('ix_friend_recipient_player_id'), table_name='friend')
    op.drop_table('friend')
    op.drop_index(op.f('ix_bag_player_id'), table_name='bag')
    op.drop_table('bag')
    op.drop_table('user_organisation_role')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_token_hash'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_player_user_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_user_organisation_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_organisation_role_organisation_id'), table_name='organisation_role')
    op.drop_table('organisation_role')
    op.drop_index(op.f('ix_access_token_token_hash'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_organisation_id'), table_name='access_token')
    op.drop_table('access_token')
    op.drop_index(op.f('ix_piece_name'), table_name='piece')
    op.drop_table('piece')
    op.drop_index(op.f('ix_organisation_slug'), table_name='organisation')
    op.drop_table('organisation')
    op.drop_table('invite')
    # ### end Alembic commands ###
