"""init

Revision ID: c3949d266cfa
Revises: 
Create Date: 2026-07-04 16:55:16.245354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3949d266cfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('room', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_room'), 'game', ['room'], unique=True)
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('input', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_log_game_id'), 'game_log', ['game_id'], unique=False)
    op.create_table('game_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_index', sa.Integer(), nullable=False),
    sa.Column('player_user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_player_game_id'), 'game_player', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_player_game_id'), table_name='game_player')
    op.drop_table('game_player')
    op.drop_index(op.f('ix_game_log_game_id'), table_name='game_log')
    op.drop_table('game_log')
    op.drop_index(op.f('ix_game_room'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
